import mongoose from 'mongoose';
import dotenv from 'dotenv';
import { Car } from './src/models/Car.js';

dotenv.config();

const seedCars = async () => {
  try {
    await mongoose.connect(process.env.DATABASE_URL || 'mongodb://localhost:27017/topspeed');
    
    // Clear existing cars
    await Car.deleteMany({});
    
    const carsData = [
      {
        brand: 'Alpine',
        model: 'A110',
        year: 2023,
        engine: { displacement: 1798, cylinders: 4, type: 'Turbocharged Inline-4' },
        horsepower: 292,
        torque: 320,
        fuelType: 'Petrol',
        acceleration: 4.4,
        topSpeed: 260,
        drivetrain: 'RWD',
        category: 'Sports',
        price: 1798000,
        imageUrl: '/images/cars/alpine_a110.jpg',
        description: 'Lightweight French sports car with exceptional handling',
        isVisible: true,
      },
      {
        brand: 'Aston Martin',
        model: 'DB11',
        year: 2023,
        engine: { displacement: 5204, cylinders: 12, type: 'Twin-Turbocharged V12' },
        horsepower: 625,
        torque: 684,
        fuelType: 'Petrol',
        acceleration: 3.9,
        topSpeed: 320,
        drivetrain: 'RWD',
        category: 'Coupe',
        price: 9300000,
        imageUrl: '/images/cars/aston_martin_db11.jpg',
        description: 'Iconic British grand tourer with stunning performance',
        isVisible: true,
      },
      {
        brand: 'Audi',
        model: 'A8 L',
        year: 2023,
        engine: { displacement: 3996, cylinders: 8, type: 'Turbocharged V8' },
        horsepower: 460,
        torque: 580,
        fuelType: 'Petrol',
        acceleration: 4.5,
        topSpeed: 250,
        drivetrain: 'AWD',
        category: 'Sedan',
        price: 3348000,
        imageUrl: '/images/cars/audi_a8_l.jpg',
        description: 'Luxury flagship sedan with cutting-edge technology',
        isVisible: true,
      },
      {
        brand: 'Audi',
        model: 'RS5',
        year: 2023,
        engine: { displacement: 2994, cylinders: 6, type: 'Turbocharged V6' },
        horsepower: 450,
        torque: 443,
        fuelType: 'Petrol',
        acceleration: 3.9,
        topSpeed: 290,
        drivetrain: 'AWD',
        category: 'Coupe',
        price: 2604000,
        imageUrl: '/images/cars/audi_rs5.jpg',
        description: 'Performance coupe with dynamic handling',
        isVisible: true,
      },
      {
        brand: 'Audi',
        model: 'RS7 Avant',
        year: 2023,
        engine: { displacement: 3996, cylinders: 8, type: 'Turbocharged V8' },
        horsepower: 591,
        torque: 590,
        fuelType: 'Petrol',
        acceleration: 3.6,
        topSpeed: 305,
        drivetrain: 'AWD',
        category: 'Sedan',
        price: 3565000,
        imageUrl: '/images/cars/audi_rs7_avant.jpg',
        description: 'Ultra-high performance station wagon',
        isVisible: true,
      },
      {
        brand: 'BAIC',
        model: 'X25',
        year: 2023,
        engine: { displacement: 1500, cylinders: 4, type: 'Inline-4' },
        horsepower: 107,
        torque: 140,
        fuelType: 'Petrol',
        acceleration: 10.5,
        topSpeed: 180,
        drivetrain: 'FWD',
        category: 'SUV',
        price: 465000,
        imageUrl: '/images/cars/baic_x25.jpg',
        description: 'Affordable compact SUV',
        isVisible: true,
      },
      {
        brand: 'Bentley',
        model: 'Continental Speed',
        year: 2023,
        engine: { displacement: 6752, cylinders: 12, type: 'Twin-Turbocharged W12' },
        horsepower: 659,
        torque: 850,
        fuelType: 'Petrol',
        acceleration: 3.6,
        topSpeed: 330,
        drivetrain: 'AWD',
        category: 'Coupe',
        price: 7750000,
        imageUrl: '/images/cars/bentley_continental_speed.jpg',
        description: 'Ultimate luxury performance coupe',
        isVisible: true,
      },
      {
        brand: 'BMW',
        model: '7 Series',
        year: 2023,
        engine: { displacement: 4395, cylinders: 8, type: 'Turbocharged V8' },
        horsepower: 516,
        torque: 553,
        fuelType: 'Petrol',
        acceleration: 4.3,
        topSpeed: 250,
        drivetrain: 'RWD',
        category: 'Sedan',
        price: 2945000,
        imageUrl: '/images/cars/bmw_7_series.jpg',
        description: 'Premium flagship luxury sedan',
        isVisible: true,
      },
      {
        brand: 'BMW',
        model: 'M3',
        year: 2023,
        engine: { displacement: 2993, cylinders: 6, type: 'Twin-Turbocharged Inline-6' },
        horsepower: 503,
        torque: 479,
        fuelType: 'Petrol',
        acceleration: 3.4,
        topSpeed: 295,
        drivetrain: 'AWD',
        category: 'Sedan',
        price: 3162000,
        imageUrl: '/images/cars/bmw_m3.jpg',
        description: 'High-performance sports sedan',
        isVisible: true,
      },
      {
        brand: 'BMW',
        model: 'M440i xDrive',
        year: 2023,
        engine: { displacement: 2998, cylinders: 6, type: 'Twin-Turbocharged Inline-6' },
        horsepower: 382,
        torque: 369,
        fuelType: 'Petrol',
        acceleration: 4.7,
        topSpeed: 250,
        drivetrain: 'AWD',
        category: 'Sedan',
        price: 2015000,
        imageUrl: '/images/cars/bmw_m440i_xdrive.jpg',
        description: 'Sporty luxury sedan with strong performance',
        isVisible: true,
      },
      {
        brand: 'Brilliance',
        model: 'V7',
        year: 2023,
        engine: { displacement: 1800, cylinders: 4, type: 'Inline-4' },
        horsepower: 131,
        torque: 170,
        fuelType: 'Petrol',
        acceleration: 9.8,
        topSpeed: 200,
        drivetrain: 'FWD',
        category: 'SUV',
        price: 620000,
        imageUrl: '/images/cars/brilliance_v7.jpg',
        description: 'Practical Chinese SUV',
        isVisible: true,
      },
      {
        brand: 'Bugatti',
        model: 'Bolide',
        year: 2023,
        engine: { displacement: 7993, cylinders: 16, type: 'Quad-Turbocharged W16' },
        horsepower: 1850,
        torque: 1106,
        fuelType: 'Petrol',
        acceleration: 2.17,
        topSpeed: 490,
        drivetrain: 'AWD',
        category: 'Sports',
        price: 46500000,
        imageUrl: '/images/cars/bugatti_bolide.jpg',
        description: 'Hypercar with extreme performance',
        isVisible: true,
      },
      {
        brand: 'Cadillac',
        model: 'CT6',
        year: 2023,
        engine: { displacement: 4395, cylinders: 8, type: 'Turbocharged V8' },
        horsepower: 550,
        torque: 647,
        fuelType: 'Petrol',
        acceleration: 4.2,
        topSpeed: 250,
        drivetrain: 'RWD',
        category: 'Sedan',
        price: 2325000,
        imageUrl: '/images/cars/cadillac_ct6.jpg',
        description: 'American luxury flagship sedan',
        isVisible: true,
      },
      {
        brand: 'Cadillac',
        model: 'Escalade',
        year: 2023,
        engine: { displacement: 6200, cylinders: 8, type: 'Naturally Aspirated V8' },
        horsepower: 420,
        torque: 460,
        fuelType: 'Petrol',
        acceleration: 6.0,
        topSpeed: 200,
        drivetrain: '4WD',
        category: 'SUV',
        price: 2480000,
        imageUrl: '/images/cars/cadillac_escalade.jpg',
        description: 'Full-size luxurious SUV',
        isVisible: true,
      },
      {
        brand: 'Changan',
        model: 'CS35',
        year: 2023,
        engine: { displacement: 1600, cylinders: 4, type: 'Inline-4' },
        horsepower: 110,
        torque: 145,
        fuelType: 'Petrol',
        acceleration: 10.2,
        topSpeed: 190,
        drivetrain: 'FWD',
        category: 'SUV',
        price: 372000,
        imageUrl: '/images/cars/changan_cs35.jpg',
        description: 'Budget-friendly compact SUV',
        isVisible: true,
      },
      {
        brand: 'Chery',
        model: 'Tiggo 7',
        year: 2023,
        engine: { displacement: 1500, cylinders: 4, type: 'Inline-4' },
        horsepower: 143,
        torque: 200,
        fuelType: 'Petrol',
        acceleration: 9.5,
        topSpeed: 210,
        drivetrain: 'FWD',
        category: 'SUV',
        price: 558000,
        imageUrl: '/images/cars/chery_tiggo_7.jpg',
        description: 'Chinese mid-size SUV',
        isVisible: true,
      },
      {
        brand: 'Chevrolet',
        model: 'Camaro ZL1',
        year: 2023,
        engine: { displacement: 6200, cylinders: 8, type: 'Supercharged V8' },
        horsepower: 650,
        torque: 650,
        fuelType: 'Petrol',
        acceleration: 3.5,
        topSpeed: 299,
        drivetrain: 'RWD',
        category: 'Sports',
        price: 1860000,
        imageUrl: '/images/cars/chevrolet_camaro_zl1.jpg',
        description: 'American muscle car with superb performance',
        isVisible: true,
      },
      {
        brand: 'Chevrolet',
        model: 'Corvette E-Ray',
        year: 2024,
        engine: { displacement: 5500, cylinders: 8, type: 'Naturally Aspirated V8' },
        horsepower: 655,
        torque: 656,
        fuelType: 'Petrol',
        acceleration: 2.9,
        topSpeed: 330,
        drivetrain: 'AWD',
        category: 'Sports',
        price: 3255000,
        imageUrl: '/images/cars/chevrolet_corvette_e_ray.jpg',
        description: 'Hybrid sports car with electric motor assistance',
        isVisible: true,
      },
      {
        brand: 'Chevrolet',
        model: 'Silverado',
        year: 2023,
        engine: { displacement: 5300, cylinders: 8, type: 'Naturally Aspirated V8' },
        horsepower: 355,
        torque: 383,
        fuelType: 'Petrol',
        acceleration: 7.0,
        topSpeed: 200,
        drivetrain: '4WD',
        category: 'Truck',
        price: 1705000,
        imageUrl: '/images/cars/chevrolet_silverado.jpg',
        description: 'Full-size pickup truck',
        isVisible: true,
      },
      {
        brand: 'Chevrolet',
        model: 'Tahoe',
        year: 2025,
        engine: { displacement: 5300, cylinders: 8, type: 'Naturally Aspirated V8' },
        horsepower: 355,
        torque: 383,
        fuelType: 'Petrol',
        acceleration: 6.8,
        topSpeed: 200,
        drivetrain: '4WD',
        category: 'SUV',
        price: 1860000,
        imageUrl: '/images/cars/chevrolet-tahoe-2025.avif',
        description: 'Full-size luxury SUV',
        isVisible: true,
      },
      {
        brand: 'Dodge',
        model: 'Challenger R/T',
        year: 2023,
        engine: { displacement: 5700, cylinders: 8, type: 'Naturally Aspirated V8' },
        horsepower: 370,
        torque: 410,
        fuelType: 'Petrol',
        acceleration: 4.9,
        topSpeed: 250,
        drivetrain: 'RWD',
        category: 'Coupe',
        price: 1085000,
        imageUrl: '/images/cars/dodge_challenger_rt.jpg',
        description: 'Classic American muscle car',
        isVisible: true,
      },
      {
        brand: 'Dodge',
        model: 'Charger Daytona',
        year: 2023,
        engine: { displacement: 7000, cylinders: 8, type: 'Naturally Aspirated V8' },
        horsepower: 645,
        torque: 629,
        fuelType: 'Petrol',
        acceleration: 3.4,
        topSpeed: 290,
        drivetrain: 'RWD',
        category: 'Sedan',
        price: 2325000,
        imageUrl: '/images/cars/dodge_charger_daytona.jpg',
        description: 'Powerful sedans with contemporary styling',
        isVisible: true,
      },
      {
        brand: 'Dodge',
        model: 'Durango',
        year: 2023,
        engine: { displacement: 5700, cylinders: 8, type: 'Naturally Aspirated V8' },
        horsepower: 360,
        torque: 390,
        fuelType: 'Petrol',
        acceleration: 6.2,
        topSpeed: 200,
        drivetrain: '4WD',
        category: 'SUV',
        price: 1488000,
        imageUrl: '/images/cars/dodge_durango.jpg',
        description: 'Three-row performance SUV',
        isVisible: true,
      },
      {
        brand: 'Dodge',
        model: 'Ram 1500',
        year: 2023,
        engine: { displacement: 5700, cylinders: 8, type: 'Naturally Aspirated V8' },
        horsepower: 395,
        torque: 410,
        fuelType: 'Petrol',
        acceleration: 6.5,
        topSpeed: 200,
        drivetrain: '4WD',
        category: 'Truck',
        price: 1798000,
        imageUrl: '/images/cars/dodge_ram_1500.jpg',
        description: 'Full-size pickup truck',
        isVisible: true,
      },
      {
        brand: 'FAW',
        model: 'Besturn B50',
        year: 2023,
        engine: { displacement: 1600, cylinders: 4, type: 'Inline-4' },
        horsepower: 110,
        torque: 145,
        fuelType: 'Petrol',
        acceleration: 10.5,
        topSpeed: 190,
        drivetrain: 'FWD',
        category: 'Sedan',
        price: 310000,
        imageUrl: '/images/cars/faw_besturn_b50.jpg',
        description: 'Budget sedan for the Chinese market',
        isVisible: true,
      },
      {
        brand: 'Ferrari',
        model: '296',
        year: 2023,
        engine: { displacement: 2992, cylinders: 6, type: 'Twin-Turbocharged V6' },
        horsepower: 818,
        torque: 849,
        fuelType: 'Petrol',
        acceleration: 2.4,
        topSpeed: 342,
        drivetrain: 'RWD',
        category: 'Sports',
        price: 13950000,
        imageUrl: '/images/cars/ferrari_296.jpg',
        description: 'Latest Ferrari hybrid supercar',
        isVisible: true,
      },
      {
        brand: 'Ferrari',
        model: '812 Superfast',
        year: 2023,
        engine: { displacement: 6496, cylinders: 12, type: 'Naturally Aspirated V12' },
        horsepower: 789,
        torque: 718,
        fuelType: 'Petrol',
        acceleration: 2.9,
        topSpeed: 320,
        drivetrain: 'RWD',
        category: 'Coupe',
        price: 10850000,
        imageUrl: '/images/cars/ferrari_812_superfast.jpg',
        description: 'Ultimate naturally-aspirated Ferrari',
        isVisible: true,
      },
      {
        brand: 'Ford',
        model: 'Explorer',
        year: 2023,
        engine: { displacement: 3000, cylinders: 6, type: 'Turbocharged Inline-6' },
        horsepower: 300,
        torque: 360,
        fuelType: 'Petrol',
        acceleration: 7.2,
        topSpeed: 200,
        drivetrain: '4WD',
        category: 'SUV',
        price: 1395000,
        imageUrl: '/images/cars/ford_explorer.jpg',
        description: 'Versatile three-row SUV',
        isVisible: true,
      },
      {
        brand: 'Ford',
        model: 'F-150',
        year: 2023,
        engine: { displacement: 5000, cylinders: 8, type: 'Naturally Aspirated V8' },
        horsepower: 400,
        torque: 410,
        fuelType: 'Petrol',
        acceleration: 6.5,
        topSpeed: 200,
        drivetrain: '4WD',
        category: 'Truck',
        price: 1550000,
        imageUrl: '/images/cars/ford_f_150.jpg',
        description: 'Americas best-selling truck',
        isVisible: true,
      },
      {
        brand: 'Ford',
        model: 'Mustang Shelby GT500',
        year: 2023,
        engine: { displacement: 5200, cylinders: 8, type: 'Supercharged V8' },
        horsepower: 760,
        torque: 625,
        fuelType: 'Petrol',
        acceleration: 3.3,
        topSpeed: 298,
        drivetrain: 'RWD',
        category: 'Coupe',
        price: 2325000,
        imageUrl: '/images/cars/ford_mustang_shelby_gt500.jpg',
        description: 'Ultimate Shelby Mustang with superb performance',
        isVisible: true,
      },
      {
        brand: 'Foton',
        model: 'Tunland',
        year: 2023,
        engine: { displacement: 2400, cylinders: 4, type: 'Inline-4 Diesel' },
        horsepower: 140,
        torque: 340,
        fuelType: 'Diesel',
        acceleration: 9.0,
        topSpeed: 180,
        drivetrain: '4WD',
        category: 'Truck',
        price: 682000,
        imageUrl: '/images/cars/foton_tunland.jpg',
        description: 'Chinese pickup truck',
        isVisible: true,
      },
      {
        brand: 'GAC',
        model: 'GS4',
        year: 2023,
        engine: { displacement: 1600, cylinders: 4, type: 'Inline-4' },
        horsepower: 197,
        torque: 320,
        fuelType: 'Petrol',
        acceleration: 8.5,
        topSpeed: 210,
        drivetrain: 'FWD',
        category: 'SUV',
        price: 775000,
        imageUrl: '/images/cars/gac_gs4.jpg',
        description: 'Popular Chinese compact SUV',
        isVisible: true,
      },
      {
        brand: 'Geely',
        model: 'Emgrand',
        year: 2023,
        engine: { displacement: 1500, cylinders: 4, type: 'Inline-4' },
        horsepower: 109,
        torque: 135,
        fuelType: 'Petrol',
        acceleration: 10.3,
        topSpeed: 190,
        drivetrain: 'FWD',
        category: 'Sedan',
        price: 341000,
        imageUrl: '/images/cars/geely_emgrand.jpg',
        description: 'Budget Chinese sedan',
        isVisible: true,
      },
      {
        brand: 'Genesis',
        model: 'Electrified G80',
        year: 2023,
        engine: { displacement: 0, cylinders: 0, type: 'Electric' },
        horsepower: 516,
        torque: 704,
        fuelType: 'Electric',
        acceleration: 4.6,
        topSpeed: 260,
        drivetrain: 'AWD',
        category: 'Sedan',
        price: 2635000,
        imageUrl: '/images/cars/genesis_electrified_g80.jpg',
        description: 'Luxury electric sedan',
        isVisible: true,
      },
      {
        brand: 'Genesis',
        model: 'G90',
        year: 2023,
        engine: { displacement: 3998, cylinders: 8, type: 'Twin-Turbocharged V8' },
        horsepower: 425,
        torque: 550,
        fuelType: 'Petrol',
        acceleration: 4.8,
        topSpeed: 250,
        drivetrain: 'RWD',
        category: 'Sedan',
        price: 2852000,
        imageUrl: '/images/cars/genesis_g90.jpg',
        description: 'Luxury flagship sedan',
        isVisible: true,
      },
      {
        brand: 'GMC',
        model: 'Sierra',
        year: 2023,
        engine: { displacement: 5300, cylinders: 8, type: 'Naturally Aspirated V8' },
        horsepower: 355,
        torque: 383,
        fuelType: 'Petrol',
        acceleration: 6.8,
        topSpeed: 200,
        drivetrain: '4WD',
        category: 'Truck',
        price: 1705000,
        imageUrl: '/images/cars/gmc_sierra.jpg',
        description: 'Full-size GMC pickup truck',
        isVisible: true,
      },
      {
        brand: 'Honda',
        model: 'Accord',
        year: 2023,
        engine: { displacement: 1998, cylinders: 4, type: 'Turbocharged Inline-4' },
        horsepower: 252,
        torque: 273,
        fuelType: 'Petrol',
        acceleration: 6.7,
        topSpeed: 225,
        drivetrain: 'FWD',
        category: 'Sedan',
        price: 930000,
        imageUrl: '/images/cars/honda_accord.jpg',
        description: 'Reliable family sedan',
        isVisible: true,
      },
      {
        brand: 'Honda',
        model: 'Civic',
        year: 2023,
        engine: { displacement: 1498, cylinders: 4, type: 'Turbocharged Inline-4' },
        horsepower: 180,
        torque: 177,
        fuelType: 'Petrol',
        acceleration: 7.5,
        topSpeed: 200,
        drivetrain: 'FWD',
        category: 'Sedan',
        price: 775000,
        imageUrl: '/images/cars/honda_civic.jpg',
        description: 'Compact sporty sedan',
        isVisible: true,
      },
      {
        brand: 'Hyundai',
        model: 'Elantra',
        year: 2023,
        engine: { displacement: 2000, cylinders: 4, type: 'Naturally Aspirated Inline-4' },
        horsepower: 147,
        torque: 132,
        fuelType: 'Petrol',
        acceleration: 8.5,
        topSpeed: 200,
        drivetrain: 'FWD',
        category: 'Sedan',
        price: 713000,
        imageUrl: '/images/cars/hyundai_elantra.jpg',
        description: 'Budget-friendly compact sedan',
        isVisible: true,
      },
      {
        brand: 'Hyundai',
        model: 'Sonata',
        year: 2023,
        engine: { displacement: 2500, cylinders: 4, type: 'Naturally Aspirated Inline-4' },
        horsepower: 191,
        torque: 181,
        fuelType: 'Petrol',
        acceleration: 7.2,
        topSpeed: 210,
        drivetrain: 'FWD',
        category: 'Sedan',
        price: 992000,
        imageUrl: '/images/cars/hyundai_sonata.jpg',
        description: 'Midsize family sedan',
        isVisible: true,
      },
      {
        brand: 'Infiniti',
        model: 'Q70',
        year: 2023,
        engine: { displacement: 3696, cylinders: 8, type: 'Naturally Aspirated V8' },
        horsepower: 420,
        torque: 383,
        fuelType: 'Petrol',
        acceleration: 5.1,
        topSpeed: 250,
        drivetrain: 'RWD',
        category: 'Sedan',
        price: 2015000,
        imageUrl: '/images/cars/infiniti_q70.jpg',
        description: 'Luxury performance sedan',
        isVisible: true,
      },
      {
        brand: 'Jaguar',
        model: 'F-Type 2025',
        year: 2025,
        engine: { displacement: 5000, cylinders: 8, type: 'Supercharged V8' },
        horsepower: 575,
        torque: 516,
        fuelType: 'Petrol',
        acceleration: 4.0,
        topSpeed: 300,
        drivetrain: 'RWD',
        category: 'Coupe',
        price: 3379000,
        imageUrl: '/images/cars/jaguar_f_type_2025.jpg',
        description: 'Sleek British sports car',
        isVisible: true,
      },
      {
        brand: 'Jaguar',
        model: 'F-Type R',
        year: 2023,
        engine: { displacement: 5000, cylinders: 8, type: 'Supercharged V8' },
        horsepower: 575,
        torque: 516,
        fuelType: 'Petrol',
        acceleration: 3.9,
        topSpeed: 300,
        drivetrain: 'RWD',
        category: 'Coupe',
        price: 3255000,
        imageUrl: '/images/cars/jaguar_f_type_r.jpg',
        description: 'High-performance sports car',
        isVisible: true,
      },
      {
        brand: 'Jaguar',
        model: 'XJ',
        year: 2023,
        engine: { displacement: 3000, cylinders: 6, type: 'Supercharged Inline-6' },
        horsepower: 340,
        torque: 332,
        fuelType: 'Petrol',
        acceleration: 5.9,
        topSpeed: 250,
        drivetrain: 'RWD',
        category: 'Sedan',
        price: 2325000,
        imageUrl: '/images/cars/jaguar_xj.jpg',
        description: 'Luxury sedan with dynamic handling',
        isVisible: true,
      },
      {
        brand: 'Jeep',
        model: 'Grand Cherokee',
        year: 2023,
        engine: { displacement: 3600, cylinders: 6, type: 'Naturally Aspirated V6' },
        horsepower: 290,
        torque: 260,
        fuelType: 'Petrol',
        acceleration: 8.1,
        topSpeed: 200,
        drivetrain: '4WD',
        category: 'SUV',
        price: 1302000,
        imageUrl: '/images/cars/jeep_grand_cherokee.jpg',
        description: 'Off-road capable mid-size SUV',
        isVisible: true,
      },
      {
        brand: 'Jeep',
        model: 'Wrangler',
        year: 2023,
        engine: { displacement: 3600, cylinders: 6, type: 'Naturally Aspirated V6' },
        horsepower: 285,
        torque: 260,
        fuelType: 'Petrol',
        acceleration: 8.5,
        topSpeed: 180,
        drivetrain: '4WD',
        category: 'SUV',
        price: 1085000,
        imageUrl: '/images/cars/jeep_wrangler.jpg',
        description: 'Iconic off-road SUV',
        isVisible: true,
      },
      {
        brand: 'Kia',
        model: 'Cerato',
        year: 2023,
        engine: { displacement: 1600, cylinders: 4, type: 'Inline-4' },
        horsepower: 123,
        torque: 156,
        fuelType: 'Petrol',
        acceleration: 9.2,
        topSpeed: 195,
        drivetrain: 'FWD',
        category: 'Sedan',
        price: 558000,
        imageUrl: '/images/cars/kia_cerato.jpg',
        description: 'Budget-friendly compact sedan',
        isVisible: true,
      },
      {
        brand: 'Kia',
        model: 'Stinger',
        year: 2023,
        engine: { displacement: 3800, cylinders: 8, type: 'Naturally Aspirated V8' },
        horsepower: 368,
        torque: 376,
        fuelType: 'Petrol',
        acceleration: 5.2,
        topSpeed: 250,
        drivetrain: 'RWD',
        category: 'Sedan',
        price: 1705000,
        imageUrl: '/images/cars/kia_stinger.jpg',
        description: 'Performance sports sedan',
        isVisible: true,
      },
      {
        brand: 'Lamborghini',
        model: 'Revuelto',
        year: 2023,
        engine: { displacement: 6498, cylinders: 12, type: 'Naturally Aspirated V12' },
        horsepower: 1001,
        torque: 1000,
        fuelType: 'Petrol',
        acceleration: 2.5,
        topSpeed: 350,
        drivetrain: 'AWD',
        category: 'Sports',
        price: 15500000,
        imageUrl: '/images/cars/lamborghini_revuelto.jpg',
        description: 'First plug-in hybrid Lamborghini',
        isVisible: true,
      },
      {
        brand: 'Lexus',
        model: 'LS 500',
        year: 2023,
        engine: { displacement: 3445, cylinders: 6, type: 'Twin-Turbocharged V6' },
        horsepower: 416,
        torque: 442,
        fuelType: 'Petrol',
        acceleration: 4.7,
        topSpeed: 250,
        drivetrain: 'RWD',
        category: 'Sedan',
        price: 2480000,
        imageUrl: '/images/cars/lexus_ls_500.jpg',
        description: 'Luxury flagship sedan',
        isVisible: true,
      },
      {
        brand: 'Lexus',
        model: 'RC F',
        year: 2023,
        engine: { displacement: 5000, cylinders: 8, type: 'Naturally Aspirated V8' },
        horsepower: 472,
        torque: 391,
        fuelType: 'Petrol',
        acceleration: 4.3,
        topSpeed: 270,
        drivetrain: 'RWD',
        category: 'Coupe',
        price: 2325000,
        imageUrl: '/images/cars/lexus_rc_f.jpg',
        description: 'High-performance luxury coupe',
        isVisible: true,
      },
      {
        brand: 'Lincoln',
        model: 'Continental',
        year: 2023,
        engine: { displacement: 3500, cylinders: 6, type: 'Twin-Turbocharged V6' },
        horsepower: 400,
        torque: 415,
        fuelType: 'Petrol',
        acceleration: 5.2,
        topSpeed: 250,
        drivetrain: 'RWD',
        category: 'Sedan',
        price: 1860000,
        imageUrl: '/images/cars/lincoln_continental.jpg',
        description: 'Full-size luxury sedan',
        isVisible: true,
      },
      {
        brand: 'Lincoln',
        model: 'Navigator',
        year: 2023,
        engine: { displacement: 3500, cylinders: 6, type: 'Twin-Turbocharged V6' },
        horsepower: 440,
        torque: 510,
        fuelType: 'Petrol',
        acceleration: 5.9,
        topSpeed: 200,
        drivetrain: '4WD',
        category: 'SUV',
        price: 2635000,
        imageUrl: '/images/cars/lincoln_navigator.jpg',
        description: 'Luxury full-size SUV',
        isVisible: true,
      },
      {
        brand: 'Lotus',
        model: 'Evora',
        year: 2023,
        engine: { displacement: 3456, cylinders: 6, type: 'Supercharged V6' },
        horsepower: 416,
        torque: 398,
        fuelType: 'Petrol',
        acceleration: 3.9,
        topSpeed: 305,
        drivetrain: 'RWD',
        category: 'Sports',
        price: 3565000,
        imageUrl: '/images/cars/lotus_evora.jpg',
        description: 'British sports car with stunning handling',
        isVisible: true,
      },
      {
        brand: 'Maserati',
        model: 'Quattroporte',
        year: 2023,
        engine: { displacement: 3800, cylinders: 8, type: 'Naturally Aspirated V8' },
        horsepower: 530,
        torque: 449,
        fuelType: 'Petrol',
        acceleration: 4.5,
        topSpeed: 290,
        drivetrain: 'RWD',
        category: 'Sedan',
        price: 3720000,
        imageUrl: '/images/cars/maserati_quattroporte.jpg',
        description: 'Italian luxury performance sedan',
        isVisible: true,
      },
      {
        brand: 'Mazda',
        model: 'Mazda6',
        year: 2023,
        engine: { displacement: 2496, cylinders: 4, type: 'Naturally Aspirated Inline-4' },
        horsepower: 187,
        torque: 186,
        fuelType: 'Petrol',
        acceleration: 7.5,
        topSpeed: 210,
        drivetrain: 'FWD',
        category: 'Sedan',
        price: 868000,
        imageUrl: '/images/cars/mazda_mazda6.jpg',
        description: 'Sporty sedan with excellent handling',
        isVisible: true,
      },
      {
        brand: 'McLaren',
        model: 'Artura',
        year: 2023,
        engine: { displacement: 3994, cylinders: 8, type: 'Twin-Turbocharged V8' },
        horsepower: 680,
        torque: 720,
        fuelType: 'Petrol',
        acceleration: 3.0,
        topSpeed: 330,
        drivetrain: 'RWD',
        category: 'Sports',
        price: 10850000,
        imageUrl: '/images/cars/mclaren_artura.jpg',
        description: 'Latest McLaren supercar with hybrid power',
        isVisible: true,
      },
      {
        brand: 'Mercedes-Benz',
        model: 'AMG C43',
        year: 2023,
        engine: { displacement: 2000, cylinders: 4, type: 'Turbocharged Inline-4' },
        horsepower: 402,
        torque: 369,
        fuelType: 'Petrol',
        acceleration: 4.6,
        topSpeed: 250,
        drivetrain: 'AWD',
        category: 'Sedan',
        price: 2015000,
        imageUrl: '/images/cars/mercedes_benz_amg_c43.jpg',
        description: 'Compact performance sedan',
        isVisible: true,
      },
      {
        brand: 'Mercedes-Maybach',
        model: 'S580',
        year: 2023,
        engine: { displacement: 4663, cylinders: 8, type: 'Twin-Turbocharged V8' },
        horsepower: 530,
        torque: 626,
        fuelType: 'Petrol',
        acceleration: 4.4,
        topSpeed: 250,
        drivetrain: 'RWD',
        category: 'Sedan',
        price: 5580000,
        imageUrl: '/images/cars/mercedes_maybach_s580.jpg',
        description: 'Ultra-luxury sedan',
        isVisible: true,
      },
      {
        brand: 'MG',
        model: 'RX5',
        year: 2023,
        engine: { displacement: 1500, cylinders: 4, type: 'Inline-4' },
        horsepower: 171,
        torque: 275,
        fuelType: 'Petrol',
        acceleration: 8.5,
        topSpeed: 210,
        drivetrain: 'FWD',
        category: 'SUV',
        price: 620000,
        imageUrl: '/images/cars/mg_rx5.jpg',
        description: 'Chinese compact SUV',
        isVisible: true,
      },
      {
        brand: 'Mitsubishi',
        model: 'Lancer',
        year: 2023,
        engine: { displacement: 1998, cylinders: 4, type: 'Inline-4' },
        horsepower: 148,
        torque: 184,
        fuelType: 'Petrol',
        acceleration: 8.3,
        topSpeed: 200,
        drivetrain: 'FWD',
        category: 'Sedan',
        price: 682000,
        imageUrl: '/images/cars/mitsubishi_lancer.jpg',
        description: 'Compact sedan',
        isVisible: true,
      },
      {
        brand: 'Nissan',
        model: '370Z Nismo',
        year: 2023,
        engine: { displacement: 3696, cylinders: 6, type: 'Naturally Aspirated V6' },
        horsepower: 349,
        torque: 274,
        fuelType: 'Petrol',
        acceleration: 4.8,
        topSpeed: 250,
        drivetrain: 'RWD',
        category: 'Sports',
        price: 1395000,
        imageUrl: '/images/cars/nissan_370z_nismo.jpg',
        description: 'Sports coupe with legendary engine',
        isVisible: true,
      },
      {
        brand: 'Nissan',
        model: 'Altima',
        year: 2023,
        engine: { displacement: 2488, cylinders: 4, type: 'Naturally Aspirated Inline-4' },
        horsepower: 182,
        torque: 178,
        fuelType: 'Petrol',
        acceleration: 7.4,
        topSpeed: 210,
        drivetrain: 'FWD',
        category: 'Sedan',
        price: 837000,
        imageUrl: '/images/cars/nissan_altima.jpg',
        description: 'Reliable midsize sedan',
        isVisible: true,
      },
      {
        brand: 'Nissan',
        model: 'Z350 GTR',
        year: 2023,
        engine: { displacement: 3799, cylinders: 6, type: 'Twin-Turbocharged Inline-6' },
        horsepower: 565,
        torque: 467,
        fuelType: 'Petrol',
        acceleration: 2.8,
        topSpeed: 310,
        drivetrain: 'AWD',
        category: 'Sports',
        price: 3565000,
        imageUrl: '/images/cars/nissan_z350_gtr.jpg',
        description: 'Legendary Japanese sports car',
        isVisible: true,
      },
      {
        brand: 'Porsche',
        model: '718 Cayman',
        year: 2023,
        engine: { displacement: 2981, cylinders: 6, type: 'Twin-Turbocharged Flat-6' },
        horsepower: 443,
        torque: 406,
        fuelType: 'Petrol',
        acceleration: 4.0,
        topSpeed: 293,
        drivetrain: 'RWD',
        category: 'Sports',
        price: 2542000,
        imageUrl: '/images/cars/porsche_718_cayman.jpg',
        description: 'Midrange Porsche sports car',
        isVisible: true,
      },
      {
        brand: 'Porsche',
        model: '911 Turbo S',
        year: 2023,
        engine: { displacement: 3745, cylinders: 6, type: 'Twin-Turbocharged Flat-6' },
        horsepower: 650,
        torque: 553,
        fuelType: 'Petrol',
        acceleration: 2.7,
        topSpeed: 330,
        drivetrain: 'AWD',
        category: 'Sports',
        price: 6200000,
        imageUrl: '/images/cars/porsche_911_turbo_s.jpg',
        description: 'Top-tier Porsche with extreme performance',
        isVisible: true,
      },
      {
        brand: 'Porsche',
        model: 'Panamera',
        year: 2023,
        engine: { displacement: 2995, cylinders: 6, type: 'Twin-Turbocharged V6' },
        horsepower: 503,
        torque: 443,
        fuelType: 'Petrol',
        acceleration: 4.1,
        topSpeed: 285,
        drivetrain: 'AWD',
        category: 'Sedan',
        price: 3255000,
        imageUrl: '/images/cars/porsche_panamera.jpg',
        description: 'Sports sedan with Porsche performance',
        isVisible: true,
      },
      {
        brand: 'Rolls-Royce',
        model: 'Cullinan',
        year: 2023,
        engine: { displacement: 6752, cylinders: 12, type: 'Twin-Turbocharged V12' },
        horsepower: 563,
        torque: 627,
        fuelType: 'Petrol',
        acceleration: 5.2,
        topSpeed: 250,
        drivetrain: 'AWD',
        category: 'SUV',
        price: 10230000,
        imageUrl: '/images/cars/rolls_royce_cullinan.jpg',
        description: 'Ultimate ultra-luxury SUV',
        isVisible: true,
      },
      {
        brand: 'Rolls-Royce',
        model: 'Ghost Black Badge',
        year: 2023,
        engine: { displacement: 6752, cylinders: 12, type: 'Twin-Turbocharged V12' },
        horsepower: 630,
        torque: 826,
        fuelType: 'Petrol',
        acceleration: 4.5,
        topSpeed: 250,
        drivetrain: 'RWD',
        category: 'Sedan',
        price: 11780000,
        imageUrl: '/images/cars/rolls_royce_ghost_black_badge.jpg',
        description: 'Ultra-luxury sedan with sinister styling',
        isVisible: true,
      },
      {
        brand: 'SAIC',
        model: 'Maxus T60',
        year: 2023,
        engine: { displacement: 2400, cylinders: 4, type: 'Inline-4 Diesel' },
        horsepower: 163,
        torque: 390,
        fuelType: 'Diesel',
        acceleration: 8.5,
        topSpeed: 180,
        drivetrain: '4WD',
        category: 'Truck',
        price: 868000,
        imageUrl: '/images/cars/saic_maxus_t60.jpg',
        description: 'Chinese pickup truck',
        isVisible: true,
      },
      {
        brand: 'Soueast',
        model: 'DX3',
        year: 2023,
        engine: { displacement: 1500, cylinders: 4, type: 'Inline-4' },
        horsepower: 110,
        torque: 145,
        fuelType: 'Petrol',
        acceleration: 10.5,
        topSpeed: 190,
        drivetrain: 'FWD',
        category: 'SUV',
        price: 434000,
        imageUrl: '/images/cars/soueast_dx3.jpg',
        description: 'Budget compact SUV',
        isVisible: true,
      },
      {
        brand: 'Subaru',
        model: 'Legacy',
        year: 2023,
        engine: { displacement: 2457, cylinders: 4, type: 'Naturally Aspirated Flat-4' },
        horsepower: 182,
        torque: 176,
        fuelType: 'Petrol',
        acceleration: 7.8,
        topSpeed: 210,
        drivetrain: 'AWD',
        category: 'Sedan',
        price: 868000,
        imageUrl: '/images/cars/subaru_legacy.jpg',
        description: 'Reliable sedan with standard AWD',
        isVisible: true,
      },
      {
        brand: 'Tesla',
        model: 'Model S Plaid 2024',
        year: 2024,
        engine: { displacement: 0, cylinders: 0, type: 'Electric' },
        horsepower: 1020,
        torque: 1420,
        fuelType: 'Electric',
        acceleration: 1.99,
        topSpeed: 322,
        drivetrain: 'AWD',
        category: 'Sedan',
        price: 3068000,
        imageUrl: '/images/cars/tesla-model-s-2024.jpg',
        description: 'Fastest production sedan in the world',
        isVisible: true,
      },
      {
        brand: 'Tesla',
        model: 'Model X',
        year: 2023,
        engine: { displacement: 0, cylinders: 0, type: 'Electric' },
        horsepower: 516,
        torque: 640,
        fuelType: 'Electric',
        acceleration: 4.8,
        topSpeed: 250,
        drivetrain: 'AWD',
        category: 'SUV',
        price: 2635000,
        imageUrl: '/images/cars/tesla_model_x.jpg',
        description: 'Electric SUV with falcon wing doors',
        isVisible: true,
      },
      {
        brand: 'Toyota',
        model: 'Camry',
        year: 2023,
        engine: { displacement: 2487, cylinders: 4, type: 'Naturally Aspirated Inline-4' },
        horsepower: 203,
        torque: 184,
        fuelType: 'Petrol',
        acceleration: 7.2,
        topSpeed: 220,
        drivetrain: 'FWD',
        category: 'Sedan',
        price: 992000,
        imageUrl: '/images/cars/toyota_camry.jpg',
        description: 'Reliable family sedan',
        isVisible: true,
      },
      {
        brand: 'Toyota',
        model: 'Corolla',
        year: 2023,
        engine: { displacement: 1598, cylinders: 4, type: 'Naturally Aspirated Inline-4' },
        horsepower: 132,
        torque: 170,
        fuelType: 'Petrol',
        acceleration: 8.8,
        topSpeed: 200,
        drivetrain: 'FWD',
        category: 'Sedan',
        price: 682000,
        imageUrl: '/images/cars/toyota_corolla.jpg',
        description: 'Best-selling compact sedan',
        isVisible: true,
      },
      {
        brand: 'Wuling',
        model: 'Almaz',
        year: 2023,
        engine: { displacement: 1500, cylinders: 4, type: 'Inline-4' },
        horsepower: 139,
        torque: 220,
        fuelType: 'Petrol',
        acceleration: 9.5,
        topSpeed: 200,
        drivetrain: 'FWD',
        category: 'SUV',
        price: 496000,
        imageUrl: '/images/cars/wuling_almaz.jpg',
        description: 'Popular Chinese compact SUV',
        isVisible: true,
      },
    ];
    
    const result = await Car.insertMany(carsData);
    console.log(`✅ ${result.length} cars added to database with EGP prices`);
    
    await mongoose.disconnect();
    console.log('✅ Database seeding complete!');
  } catch (error) {
    console.error('❌ Error seeding database:', error);
    process.exit(1);
  }
};

seedCars();
